#!/usr/bin/env Rscript
# ==============================================================================
# fig2d_probe_number_histogram.R
# Probe count per gene — Flex v1 vs Flex v2 side-by-side histograms (Figure 2D)
# ==============================================================================
#
# For each expressed gene, shows the distribution of unique probe counts in the
# Flex v1 (VCC) and Flex v2 (A375) probe sets, stratified by DE status. This
# tests whether genes targeted by fewer probes are more likely to show
# probe-barcode-associated technical variation.
#
# Reads pre-computed probe count CSVs generated by 13_compute_probe_histogram_data.R.
# Each CSV has columns: gene_name, n_probe_ids, is_de.
#
# INPUT
#   results/probe_counts_vcc.csv   — from 13_compute_probe_histogram_data.R
#   results/probe_counts_a375.csv  — from 13_compute_probe_histogram_data.R
#
# OUTPUT
#   results/figures/fig2d_probe_number_histogram_v1_vs_v2.pdf
#
# USAGE
#   conda run -n trekker Rscript scripts/figure2/plot/fig2d_probe_number_histogram.R
#
# ==============================================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(patchwork)
})

RESULTS_DIR <- "results"
FIGURES_DIR <- file.path(RESULTS_DIR, "figures")
dir.create(FIGURES_DIR, showWarnings = FALSE, recursive = TRUE)

VCC_CSV  <- file.path(RESULTS_DIR, "probe_counts_vcc.csv")
A375_CSV <- file.path(RESULTS_DIR, "probe_counts_a375.csv")

for (f in c(VCC_CSV, A375_CSV)) {
  if (!file.exists(f)) {
    stop("Required file not found: ", f,
         "\nRun scripts/figure2/compute/13_compute_probe_histogram_data.R first.")
  }
}

# ==============================================================================
# Load
# ==============================================================================

probe_counts_vcc  <- read.csv(VCC_CSV)
probe_counts_a375 <- read.csv(A375_CSV)

probe_counts_vcc$is_de  <- factor(probe_counts_vcc$is_de,  levels = c("Not DE", "DE"))
probe_counts_a375$is_de <- factor(probe_counts_a375$is_de, levels = c("Not DE", "DE"))

message(sprintf("VCC  \u2014 expressed: %d | DE: %d | Not DE: %d",
  nrow(probe_counts_vcc),
  sum(probe_counts_vcc$is_de == "DE"),
  sum(probe_counts_vcc$is_de == "Not DE")))
message(sprintf("A375 \u2014 expressed: %d | DE: %d | Not DE: %d",
  nrow(probe_counts_a375),
  sum(probe_counts_a375$is_de == "DE"),
  sum(probe_counts_a375$is_de == "Not DE")))

# ==============================================================================
# Plot
# ==============================================================================

make_panel <- function(probe_counts, panel_title) {
  ggplot(probe_counts, aes(x = n_probe_ids, fill = is_de)) +
    geom_histogram(aes(y = after_stat(density)), binwidth = 1,
                   color = "black", linewidth = 0.3) +
    facet_wrap(~ is_de, ncol = 1) +
    scale_fill_manual(values = c("Not DE" = "grey60", "DE" = "tomato3"),
                      name = NULL) +
    labs(x = "Number of probes per gene", y = "Density",
         title = panel_title) +
    theme_classic() +
    theme(
      text              = element_text(color = "black"),
      plot.title        = element_text(size = 22, hjust = 0.5, color = "black"),
      axis.title        = element_text(size = 20, color = "black"),
      axis.text         = element_text(size = 17, color = "black"),
      axis.ticks        = element_line(color = "black"),
      axis.ticks.length = unit(0.15, "cm"),
      axis.line         = element_line(color = "black", linewidth = 0.6),
      panel.border      = element_blank(),
      panel.grid.major  = element_blank(),
      panel.grid.minor  = element_blank(),
      strip.background  = element_blank(),
      strip.text        = element_blank(),
      legend.position   = c(0.95, 0.95),
      legend.justification = c(1, 1),
      legend.key.spacing.y = unit(4, "pt"),
      legend.text       = element_text(size = 17, color = "black")
    )
}

p <- make_panel(probe_counts_vcc,  "Flex v1") +
     make_panel(probe_counts_a375, "Flex v2") +
     plot_layout(guides = "collect") &
     theme(legend.position = "bottom")

ggsave(file.path(FIGURES_DIR, "fig2d_probe_number_histogram_v1_vs_v2.pdf"),
       p, width = 10, height = 5, device = cairo_pdf)
message("Saved: fig2d_probe_number_histogram_v1_vs_v2.pdf")

message("Done.")
print(sessionInfo())
